### PR TITLE
feat: adding basic stats to mobile ranking

### PR DESCRIPTION
**Pull request by motzel**
image

### CODE REVIEW

**Comment by wolfcomp** [comment]
Check if this messes up the country rank implementation size of the top row.

**Comment by motzel** [comment]
I checked it out before I made the PR

image

**Comment by Umbranoxio** [comment]
I'm not sure why we need this when we have this? 
image
In my opinion it makes the page look rather clunky

**Comment by motzel** [comment]
Well, for the very same reason it's displayed in the desktop version. The ranking is based on PPs and it is important to see at glance if the difference between players is 5pp or 500pp. Without constantly clicking on individual players and going back to the ranking.

**Comment by Umbranoxio** [comment]
While I can agree with the sentiment of having things available at a glance, to the average person I feel the UX would be rather confusing, a lot of unexplained data.

**Comment by motzel** [comment]
I think the data explains itself with their suffixes. Any person who uses SS knows what PP or % is. Also under this assumption the scores are confusing as well.

image

Same data, no explanation.

IMO, the current implementation looks like there is a bug - no data, and on top of that third the screen, so valuable on mobile, is blank.

image

**Pull request merged**
